import math
import os
import requests


def query_prometheus(promql, datasource_id=1, timeout=5):
    base_url = os.environ["GRAFANA_BASE_URL"]
    auth = (os.environ["GRAFANA_USER"], os.environ["GRAFANA_PASSWORD"])
    resp = requests.get(
        f"{base_url}/api/datasources/proxy/{datasource_id}/api/v1/query",
        params={"query": promql},
        auth=auth,
        timeout=timeout,
    )
    resp.raise_for_status()
    return resp.json()


def _scalar(promql):
    result = query_prometheus(promql)
    return float(result["data"]["result"][0]["value"][1])


def _vector(promql):
    result = query_prometheus(promql)
    return result["data"]["result"]


def get_service_trace_metrics(window="30m"):
    """
    Uses Tempo span metrics (traces_spanmetrics_*) generated by the Tempo metrics generator.
    Covers all iot-core-* services via the 'service' label (not 'job').
    Latency unit: seconds (multiply by 1000 for ms).
    status_code='STATUS_CODE_ERROR' only appears when errors are actively traced.

    Returns None if Tempo span metrics are not scraped in Prometheus.
    """
    total_r = _vector(
        f'sum by(service)(rate(traces_spanmetrics_calls_total[{window}]))'
    )
    if not total_r:
        return None

    # Error spans — only present when errors occur; empty result means zero errors
    error_r = _vector(
        f'sum by(service)(rate(traces_spanmetrics_calls_total{{status_code="STATUS_CODE_ERROR"}}[{window}]))'
    )

    # P95 latency per service across all span kinds (seconds)
    p95_r = _vector(
        f'histogram_quantile(0.95,sum by(service,le)'
        f'(rate(traces_spanmetrics_latency_bucket[{window}])))'
    )

    call_rate_by_svc = {}
    for r in total_r:
        svc = r["metric"].get("service", "unknown")
        v = float(r["value"][1])
        if not math.isnan(v):
            call_rate_by_svc[svc] = round(v, 6)
    call_rate_by_svc = dict(sorted(call_rate_by_svc.items(), key=lambda x: x[1], reverse=True))

    error_rate_by_svc = {}
    for r in error_r:
        svc = r["metric"].get("service", "unknown")
        v = float(r["value"][1])
        if not math.isnan(v):
            error_rate_by_svc[svc] = round(v, 6)

    latency_p95_by_svc = {}
    for r in p95_r:
        svc = r["metric"].get("service", "unknown")
        v = _nan_to_none(float(r["value"][1]))
        if v is not None:
            latency_p95_by_svc[svc] = round(v * 1000, 3)  # convert to ms

    total_call_rate = sum(call_rate_by_svc.values())
    total_error_rate = sum(error_rate_by_svc.values())
    fleet_error_pct = (total_error_rate / total_call_rate * 100) if total_call_rate > 0 else 0.0

    if fleet_error_pct >= 2.0:
        level = "critical"
    elif fleet_error_pct >= 0.5:
        level = "warning"
    else:
        level = "good"

    return {
        "fleet_call_rate_per_sec": round(total_call_rate, 6),
        "fleet_error_rate_pct": round(fleet_error_pct, 4),
        "call_rate_by_service": call_rate_by_svc,
        "error_rate_by_service": error_rate_by_svc,
        "latency_p95_ms_by_service": latency_p95_by_svc,
        "level": level,
        "window": window,
    }


def get_java_error_rate(window="30m"):
    """Backward-compatible alias — delegates to get_service_trace_metrics."""
    return get_service_trace_metrics(window=window)


def _nan_to_none(v):
    return None if (v is None or math.isnan(v)) else v


def _per_service(results):
    """Convert a Prometheus vector result into {job: value} dict, sorted by value desc."""
    out = {}
    for r in results:
        job = r["metric"].get("job") or r["metric"].get("service_name", "unknown")
        v = float(r["value"][1])
        if not math.isnan(v):
            out[job] = round(v, 6)
    return dict(sorted(out.items(), key=lambda x: x[1], reverse=True))


def get_otel_service_metrics(job=".+", window="30m"):
    """
    All Prometheus panels from 'OpenTelemetry Metrics Dashboard (No Traces/Logs) 2'
    (uid=otlp-metrics-only-dashboard2):
      - HTTP: request rate, error rate %, latency P95 (per service + fleet total)
      - JVM: CPU utilization, heap %, non-heap %, thread count, GC time (per service)
      - DB (MongoDB/MySQL): operations rate, P50/P95/P99 duration (per service)
      - Cache (Redis): operations rate, P50/P95 duration (per service)

    Level thresholds (HTTP error rate, Bo_chi_so API Success Rate / Core):
      good < 0.5% | warning 0.5-2% | critical >= 2%
    """
    jf = f'job=~"{job}"'

    # ── HTTP ──────────────────────────────────────────────────────────────────
    http_count = (
        "http_server_request_duration_seconds_count"
        "|http_server_request_duration_count"
        "|http_server_duration_seconds_count"
        "|http_server_duration_count"
    )
    http_bucket = (
        "http_server_request_duration_seconds_bucket"
        "|http_server_request_duration_bucket"
        "|http_server_duration_seconds_bucket"
        "|http_server_duration_bucket"
    )

    total_r = _vector(f'sum by(job)(rate({{__name__=~"{http_count}",{jf}}}[{window}]))')
    error_5xx_r = _vector(
        f'sum by(job)(rate({{__name__=~"http_server_request_duration_seconds_count'
        f'|http_server_request_duration_count",{jf},'
        f'http_response_status_code=~"5.*"}}[{window}]))'
    )
    error_4xx_r = _vector(
        f'sum by(job)(rate({{__name__=~"http_server_request_duration_seconds_count'
        f'|http_server_request_duration_count",{jf},'
        f'http_response_status_code=~"4.*"}}[{window}]))'
    )
    latency_p50_r = _vector(
        f'histogram_quantile(0.50,sum by(job,le)'
        f'(rate({{__name__=~"{http_bucket}",{jf}}}[{window}])))'
    )
    latency_p95_r = _vector(
        f'histogram_quantile(0.95,sum by(job,le)'
        f'(rate({{__name__=~"{http_bucket}",{jf}}}[{window}])))'
    )
    latency_p99_r = _vector(
        f'histogram_quantile(0.99,sum by(job,le)'
        f'(rate({{__name__=~"{http_bucket}",{jf}}}[{window}])))'
    )

    total_by_svc = _per_service(total_r)
    error_by_svc = _per_service(error_5xx_r)
    error_4xx_by_svc = _per_service(error_4xx_r)

    def _latency_dict(vec):
        return {
            r["metric"].get("job", "unknown"): _nan_to_none(float(r["value"][1]))
            for r in vec
        }

    latency_p50_by_svc = _latency_dict(latency_p50_r)
    latency_p95_by_svc = _latency_dict(latency_p95_r)
    latency_p99_by_svc = _latency_dict(latency_p99_r)

    fleet_total = sum(total_by_svc.values())
    fleet_errors = sum(error_by_svc.values())
    fleet_4xx = sum(error_4xx_by_svc.values())
    fleet_error_pct = (fleet_errors / fleet_total * 100) if fleet_total > 0 else 0.0
    fleet_4xx_pct = (fleet_4xx / fleet_total * 100) if fleet_total > 0 else 0.0

    error_rate_pct_by_svc = {
        svc: round(error_by_svc.get(svc, 0) / total_by_svc[svc] * 100, 4)
        for svc in total_by_svc
        if total_by_svc[svc] > 0
    }

    if fleet_error_pct < 0.5:
        http_level = "good"
    elif fleet_error_pct < 2.0:
        http_level = "warning"
    else:
        http_level = "critical"

    # ── JVM ──────────────────────────────────────────────────────────────────
    jvm_cpu_r = _vector(f'jvm_cpu_recent_utilization_ratio{{{jf}}}')
    jvm_cpu = _per_service(jvm_cpu_r)

    heap_used_r = _vector(f'sum by(job)(jvm_memory_used_bytes{{{jf},jvm_memory_type="heap"}})')
    heap_max_r  = _vector(f'sum by(job)(jvm_memory_limit_bytes{{{jf},jvm_memory_type="heap"}})')
    heap_used = {r["metric"].get("job","?"): float(r["value"][1]) for r in heap_used_r}
    heap_max  = {r["metric"].get("job","?"): float(r["value"][1]) for r in heap_max_r}
    heap_pct  = {
        svc: round(heap_used[svc] / heap_max[svc] * 100, 2)
        for svc in heap_used if svc in heap_max and heap_max[svc] > 0
    }

    non_heap_used_r = _vector(f'sum by(job)(jvm_memory_used_bytes{{{jf},jvm_memory_type="non_heap"}})')
    non_heap_max_r  = _vector(f'sum by(job)(jvm_memory_limit_bytes{{{jf},jvm_memory_type="non_heap"}})')
    non_heap_used = {r["metric"].get("job","?"): float(r["value"][1]) for r in non_heap_used_r}
    non_heap_max  = {r["metric"].get("job","?"): float(r["value"][1]) for r in non_heap_max_r}
    non_heap_pct  = {
        svc: round(non_heap_used[svc] / non_heap_max[svc] * 100, 2)
        for svc in non_heap_used if svc in non_heap_max and non_heap_max[svc] > 0
    }

    thread_r = _vector(f'sum by(job)(jvm_thread_count{{{jf}}})')
    threads = _per_service(thread_r)

    gc_r = _vector(f'sum by(job)(rate(jvm_gc_duration_sum{{{jf}}}[{window}]))')
    gc_time = _per_service(gc_r)

    # ── DB (MongoDB / MySQL) ──────────────────────────────────────────────────
    db_f = f'{jf},db_system_name=~"mongodb|mysql"'
    db_ops_r = _vector(
        f'sum by(job)(rate(db_client_operation_duration_seconds_count{{{db_f}}}[{window}]))'
    )
    db_ops = _per_service(db_ops_r)

    db_p50_r = _vector(
        f'histogram_quantile(0.50,sum by(job,le)'
        f'(rate(db_client_operation_duration_seconds_bucket{{{db_f}}}[{window}])))'
    )
    db_p95_r = _vector(
        f'histogram_quantile(0.95,sum by(job,le)'
        f'(rate(db_client_operation_duration_seconds_bucket{{{db_f}}}[{window}])))'
    )
    db_p99_r = _vector(
        f'histogram_quantile(0.99,sum by(job,le)'
        f'(rate(db_client_operation_duration_seconds_bucket{{{db_f}}}[{window}])))'
    )
    db_p50 = {r["metric"].get("job","?"): _nan_to_none(float(r["value"][1])) for r in db_p50_r}
    db_p95 = {r["metric"].get("job","?"): _nan_to_none(float(r["value"][1])) for r in db_p95_r}
    db_p99 = {r["metric"].get("job","?"): _nan_to_none(float(r["value"][1])) for r in db_p99_r}

    # ── Cache (Redis) ─────────────────────────────────────────────────────────
    cache_f = f'{jf},db_system_name="redis"'
    cache_ops_r = _vector(
        f'sum by(job)(rate(db_client_operation_duration_seconds_count{{{cache_f}}}[{window}]))'
    )
    cache_ops = _per_service(cache_ops_r)

    cache_p50_r = _vector(
        f'histogram_quantile(0.50,sum by(job,le)'
        f'(rate(db_client_operation_duration_seconds_bucket{{{cache_f}}}[{window}])))'
    )
    cache_p95_r = _vector(
        f'histogram_quantile(0.95,sum by(job,le)'
        f'(rate(db_client_operation_duration_seconds_bucket{{{cache_f}}}[{window}])))'
    )
    cache_p50 = {r["metric"].get("job","?"): _nan_to_none(float(r["value"][1])) for r in cache_p50_r}
    cache_p95 = {r["metric"].get("job","?"): _nan_to_none(float(r["value"][1])) for r in cache_p95_r}

    return {
        "window": window,
        "http": {
            "fleet_request_rate_per_sec": round(fleet_total, 6),
            "fleet_error_rate_pct": round(fleet_error_pct, 4),
            "fleet_4xx_rate_pct": round(fleet_4xx_pct, 4),
            "request_rate_by_service": total_by_svc,
            "error_rate_by_service": error_by_svc,
            "error_4xx_by_service": error_4xx_by_svc,
            "error_rate_pct_by_service": error_rate_pct_by_svc,
            "latency_p50_sec_by_service": latency_p50_by_svc,
            "latency_p95_sec_by_service": latency_p95_by_svc,
            "latency_p99_sec_by_service": latency_p99_by_svc,
            "level": http_level,
        },
        "jvm": {
            "cpu_utilization_by_service": jvm_cpu,
            "heap_utilization_pct_by_service": heap_pct,
            "non_heap_utilization_pct_by_service": non_heap_pct,
            "thread_count_by_service": threads,
            "gc_time_rate_by_service": gc_time,
        },
        "db": {
            "operations_rate_per_sec_by_service": db_ops,
            "duration_p50_sec_by_service": db_p50,
            "duration_p95_sec_by_service": db_p95,
            "duration_p99_sec_by_service": db_p99,
        },
        "cache": {
            "operations_rate_per_sec_by_service": cache_ops,
            "duration_p50_sec_by_service": cache_p50,
            "duration_p95_sec_by_service": cache_p95,
        },
    }


# Keep old name as alias for backward compatibility
def get_http_service_health(project=".+", job=".+", window="30m"):
    result = get_otel_service_metrics(job=job, window=window)
    h = result["http"]
    return {
        "request_rate_per_sec": h["fleet_request_rate_per_sec"],
        "error_rate_per_sec": sum(h["error_rate_by_service"].values()),
        "error_rate_pct": h["fleet_error_rate_pct"],
        "latency_p95_sec": next(iter(h["latency_p95_sec_by_service"].values()), None),
        "window": window,
        "level": h["level"],
    }


def get_rabbitmq_queue_backlog():
    """
    Panels from 'RabbitMQ Queue Backlog' dashboard (uid=afl7kc08i70g0d).
    Level proxy for Bo_chi_so 'Queue Backlog' (Ingestion / Core):
      good     = total_messages == 0
      warning  = 1 <= total_messages < 100
      critical = total_messages >= 100
    """
    total_result = _vector("sum(rabbitmq_queue_messages)")
    total = int(float(total_result[0]["value"][1])) if total_result else 0

    per_queue_result = _vector("sum by(queue)(rabbitmq_queue_messages)")
    queues = sorted(
        [
            {"queue": r["metric"].get("queue", "unknown"), "messages": int(float(r["value"][1]))}
            for r in per_queue_result
        ],
        key=lambda q: q["messages"],
        reverse=True,
    )

    if total == 0:
        level = "good"
    elif total < 100:
        level = "warning"
    else:
        level = "critical"

    return {
        "total_messages": total,
        "queues": queues,
        "level": level,
    }


def get_rabbitmq_throughput(queue=".+"):
    """
    Panels from 'RabbitMQ Orchestration Throughput' dashboard (uid=dflthsv5mt05cd).
    Returns publish rate, ack rate, and lag_rate (publish - ack; positive = backpressure).
    """
    publish_result = _vector(
        f'sum(rate(rabbitmq_queue_messages_published_total{{queue=~"{queue}"}}[1m]))'
    )
    ack_result = _vector(
        f'sum(rate(rabbitmq_queue_messages_acked_total{{queue=~"{queue}"}}[1m]))'
    )

    publish_rate = float(publish_result[0]["value"][1]) if publish_result else 0.0
    ack_rate = float(ack_result[0]["value"][1]) if ack_result else 0.0

    return {
        "publish_rate_per_sec": round(publish_rate, 6),
        "ack_rate_per_sec": round(ack_rate, 6),
        "lag_rate": round(publish_rate - ack_rate, 6),
        "queue_filter": queue,
    }


# ── Loki ──────────────────────────────────────────────────────────────────────


def query_loki(logql, limit=100, start=None, end=None, timeout=10):
    import time as _time
    base_url = os.environ["GRAFANA_BASE_URL"]
    auth = (os.environ["GRAFANA_USER"], os.environ["GRAFANA_PASSWORD"])
    now = int(_time.time())
    resp = requests.get(
        f"{base_url}/api/datasources/proxy/2/loki/api/v1/query_range",
        params={
            "query": logql,
            "limit": limit,
            "start": start if start is not None else (now - 3600),
            "end": end if end is not None else now,
        },
        auth=auth,
        timeout=timeout,
    )
    resp.raise_for_status()
    return resp.json()


def get_service_logs(service=".+", level="error", limit=20, hours_back=1):
    """
    Queries Loki (datasource id=2) for recent service logs.
    iot-core-* services export logs via OTel → use 'detected_level' label (e.g. error, warn, info).
    Linux journal logs use 'level' label instead. This function queries detected_level by default.
    label 'service_name' examples: iot-core-accounting-api, emqx, iot-core-devicemgmt
    """
    import time as _time
    logql = f'{{service_name=~"{service}", detected_level=~"{level}"}}'
    now = int(_time.time())
    result = query_loki(logql, limit=limit, start=now - hours_back * 3600, end=now)
    streams = result.get("data", {}).get("result", [])
    entries = []
    for stream in streams:
        svc = stream["stream"].get("service_name", "unknown")
        lvl = stream["stream"].get("detected_level") or stream["stream"].get("level", "unknown")
        for ts_ns, msg in stream.get("values", []):
            entries.append({
                "timestamp_ns": ts_ns,
                "service_name": svc,
                "level": lvl,
                "message": msg,
            })
    entries.sort(key=lambda e: e["timestamp_ns"], reverse=True)
    return {
        "service_filter": service,
        "level_filter": level,
        "hours_back": hours_back,
        "count": len(entries),
        "entries": entries[:limit],
    }


# ── Infrastructure health ─────────────────────────────────────────────────────


def get_emqx_health():
    """
    Combines EMQX main, client-events, and messages dashboards via Prometheus.
    Level driver: message drop rate (good < 0.1/s | warning 0.1-1.0/s | critical > 1.0/s).
    """
    connections_r = _vector("sum(emqx_connections_count)")
    connections = int(float(connections_r[0]["value"][1])) if connections_r else 0

    def _rate(metric):
        r = _vector(f"sum(rate({metric}[1m]))")
        return round(float(r[0]["value"][1]), 6) if r else 0.0

    recv_rate = _rate("emqx_messages_received_total")
    sent_rate = _rate("emqx_messages_sent_total")
    drop_rate = _rate("emqx_messages_dropped_total")
    auth_rate = _rate("emqx_client_authenticate_total")
    sub_rate = _rate("emqx_client_subscribe_total")

    disconn_r = _vector("sum by(reason)(rate(emqx_client_disconnected_total[1m]))")
    disconnects_by_reason = {
        r["metric"].get("reason", "unknown"): round(float(r["value"][1]), 6)
        for r in disconn_r
    }

    if drop_rate > 1.0:
        level = "critical"
    elif drop_rate > 0.1:
        level = "warning"
    else:
        level = "good"

    return {
        "connections": connections,
        "message_received_rate": recv_rate,
        "message_sent_rate": sent_rate,
        "message_drop_rate": drop_rate,
        "auth_rate": auth_rate,
        "subscribe_rate": sub_rate,
        "disconnects_by_reason": disconnects_by_reason,
        "level": level,
    }


def get_k8s_health():
    """
    Kubernetes cluster health via Prometheus recording rules.
    Level: Failed pods > 0 or restarts > 200 → critical; restarts > 50 or CPU > 80% → warning.
    """
    cpu_r = _vector("avg(cluster:node_cpu:ratio_rate5m) * 100")
    cpu_pct = round(float(cpu_r[0]["value"][1]), 2) if cpu_r else None

    restarts_r = _vector("sum(kube_pod_container_status_restarts_total)")
    total_restarts = int(float(restarts_r[0]["value"][1])) if restarts_r else 0

    phase_r = _vector("sum by(phase)(kube_pod_status_phase)")
    pod_phases = {
        r["metric"].get("phase", "unknown"): int(float(r["value"][1]))
        for r in phase_r
    }

    mem_r = _vector('sum(container_memory_working_set_bytes{container!=""})')
    memory_used_bytes = int(float(mem_r[0]["value"][1])) if mem_r else None

    failed = pod_phases.get("Failed", 0)
    if failed > 0 or total_restarts > 200:
        level = "critical"
    elif total_restarts > 50 or (cpu_pct is not None and cpu_pct > 80):
        level = "warning"
    else:
        level = "good"

    return {
        "cluster_cpu_pct": cpu_pct,
        "total_pod_restarts": total_restarts,
        "pod_phases": pod_phases,
        "memory_used_bytes": memory_used_bytes,
        "level": level,
    }


def get_redis_health():
    """
    Redis health from Redis Overview dashboard via Prometheus.
    Level: hit_rate_pct < 50% → warning; memory_used_pct > 80% → warning.
    """
    clients_r = _vector("sum(redis_connected_clients)")
    connected_clients = int(float(clients_r[0]["value"][1])) if clients_r else 0

    ops_r = _vector("sum(rate(redis_commands_total[5m]))")
    ops_rate = round(float(ops_r[0]["value"][1]), 2) if ops_r else 0.0

    # Use raw counters for hit rate (rate() gives 0 in low-traffic periods)
    hits_r = _vector("sum(redis_keyspace_hits_total)")
    misses_r = _vector("sum(redis_keyspace_misses_total)")
    hits = float(hits_r[0]["value"][1]) if hits_r else 0.0
    misses = float(misses_r[0]["value"][1]) if misses_r else 0.0
    hit_rate_pct = round(hits / (hits + misses) * 100, 2) if (hits + misses) > 0 else None

    mem_used_r = _vector("sum(redis_memory_used_bytes)")
    mem_max_r = _vector("sum(redis_memory_max_bytes)")
    memory_used_bytes = int(float(mem_used_r[0]["value"][1])) if mem_used_r else None
    memory_max_bytes = int(float(mem_max_r[0]["value"][1])) if mem_max_r else None
    memory_used_pct = (
        round(memory_used_bytes / memory_max_bytes * 100, 2)
        if memory_used_bytes and memory_max_bytes and memory_max_bytes > 0
        else None
    )

    level = "good"
    if hit_rate_pct is not None and hit_rate_pct < 50:
        level = "warning"
    if memory_used_pct is not None and memory_used_pct > 80:
        level = "warning"

    return {
        "connected_clients": connected_clients,
        "ops_rate_per_sec": ops_rate,
        "hit_rate_pct": hit_rate_pct,
        "memory_used_bytes": memory_used_bytes,
        "memory_max_bytes": memory_max_bytes,
        "memory_used_pct": memory_used_pct,
        "level": level,
    }


def get_mongodb_health():
    """
    MongoDB health from MongoDB Overview dashboard via Prometheus.
    ops_rate_per_sec is None if mongodb_mongod_op_counters_total is absent in Prometheus.
    Level: avg_latency_ms > 100 → warning.
    """
    up_r = _vector("sum(mongodb_up)")
    instances_up = int(float(up_r[0]["value"][1])) if up_r else 0

    try:
        ops_r = _vector("sum(rate(mongodb_mongod_op_counters_total[5m]))")
        ops_rate = round(float(ops_r[0]["value"][1]), 2) if ops_r else None
    except (IndexError, KeyError):
        ops_rate = None

    try:
        lat_total_r = _vector("sum(mongodb_mongod_op_latencies_latency_total)")
        lat_ops_r = _vector("sum(mongodb_mongod_op_latencies_ops_total)")
        lat_total = float(lat_total_r[0]["value"][1]) if lat_total_r else None
        lat_ops = float(lat_ops_r[0]["value"][1]) if lat_ops_r else None
        avg_latency_ms = (
            round(lat_total / lat_ops / 1000, 3)
            if lat_total is not None and lat_ops and lat_ops > 0
            else None
        )
    except (IndexError, KeyError):
        avg_latency_ms = None

    level = "warning" if avg_latency_ms is not None and avg_latency_ms > 100 else "good"

    return {
        "instances_up": instances_up,
        "ops_rate_per_sec": ops_rate,
        "avg_latency_ms": avg_latency_ms,
        "level": level,
    }


def get_mysql_health():
    """
    MySQL health from MySQL Overview dashboard via Prometheus.
    Level: slow_queries > 0 → warning; threads_connected > 100 → warning.
    """
    up_r = _vector("sum(mysql_up)")
    instances_up = int(float(up_r[0]["value"][1])) if up_r else 0

    qps_r = _vector("sum(rate(mysql_global_status_queries[5m]))")
    qps = round(float(qps_r[0]["value"][1]), 2) if qps_r else 0.0

    threads_r = _vector("sum(mysql_global_status_threads_connected)")
    threads_connected = int(float(threads_r[0]["value"][1])) if threads_r else 0

    slow_r = _vector("sum(mysql_global_status_slow_queries)")
    slow_queries = int(float(slow_r[0]["value"][1])) if slow_r else 0

    if slow_queries > 0 or threads_connected > 100:
        level = "warning"
    else:
        level = "good"

    return {
        "instances_up": instances_up,
        "qps": qps,
        "threads_connected": threads_connected,
        "slow_queries": slow_queries,
        "level": level,
    }


def get_linux_node_health():
    """
    Linux node health from CPU and system [linux-node-integration] dashboard via Prometheus.
    Level: CPU > 85% or disk > 90% → critical; CPU > 70% or disk > 80% or memory > 85% → warning.
    """
    cpu_r = _vector(
        '(1 - avg(rate(node_cpu_seconds_total{mode="idle"}[5m]))) * 100'
    )
    cpu_pct = round(float(cpu_r[0]["value"][1]), 2) if cpu_r else None

    mem_r = _vector(
        "( 1 - avg(node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) ) * 100"
    )
    memory_pct = round(float(mem_r[0]["value"][1]), 2) if mem_r else None

    disk_r = _vector(
        'avg(1 - node_filesystem_avail_bytes{mountpoint="/"}'
        ' / node_filesystem_size_bytes{mountpoint="/"}) * 100'
    )
    disk_pct = round(float(disk_r[0]["value"][1]), 2) if disk_r else None

    net_r = _vector("sum(rate(node_network_receive_bytes_total[5m]))")
    network_receive_bytes_per_sec = round(float(net_r[0]["value"][1]), 2) if net_r else None

    if (cpu_pct is not None and cpu_pct > 85) or (disk_pct is not None and disk_pct > 90):
        level = "critical"
    elif (
        (cpu_pct is not None and cpu_pct > 70)
        or (disk_pct is not None and disk_pct > 80)
        or (memory_pct is not None and memory_pct > 85)
    ):
        level = "warning"
    else:
        level = "good"

    return {
        "cpu_usage_pct": cpu_pct,
        "memory_usage_pct": memory_pct,
        "disk_usage_pct": disk_pct,
        "network_receive_bytes_per_sec": network_receive_bytes_per_sec,
        "level": level,
    }
