POC_RULESET_VERSION = "company-poc-v1"
POC_RULE_DISCLAIMER = (
    "PoC fallback alert generated by provisional local demo rules. It is not "
    "an official company alert and must be replaced or confirmed by approved "
    "company rule semantics or Grafana."
)

POC_RULES = [
    {
        "id": "poc-device-disconnected",
        "name": "Device reported disconnected",
        "signal": "status",
        "operator": "in",
        "threshold": ["disconnected", "offline"],
        "severity": "critical",
        "description": (
            "Flags an explicit disconnected or offline status reported by "
            "the device payload."
        ),
    },
    {
        "id": "poc-temperature-high",
        "name": "High temperature",
        "signal": "temperature",
        "metric_names": ["temp", "temperature", "nhietdo"],
        "operator": ">=",
        "warning_threshold": 50,
        "critical_threshold": 70,
        "description": (
            "Demo temperature threshold. Unit interpretation still requires "
            "confirmation from the company telemetry contract."
        ),
    },
    {
        "id": "poc-rssi-weak",
        "name": "Weak signal strength",
        "signal": "rssi",
        "metric_names": ["rssi"],
        "operator": "<=",
        "warning_threshold": -70,
        "critical_threshold": -85,
        "description": (
            "Demo RSSI threshold for telemetry values explicitly named RSSI."
        ),
    },
]


def metric_leaf_name(name):
    normalized = str(name or "").strip().lower()

    if not normalized:
        return ""

    normalized = normalized.rsplit(".", 1)[-1]
    normalized = normalized.split("[", 1)[0]
    return normalized


def numeric_value(value):
    if isinstance(value, bool):
        return None

    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def build_alert(device, rule, severity, evidence):
    return {
        "alert_id": f"{rule['id']}:{device.get('device_id')}",
        "device_id": device.get("device_id"),
        "device_name": device.get("device_name"),
        "severity": severity,
        "status": "active",
        "title": rule["name"],
        "rule_id": rule["id"],
        "rule_name": rule["name"],
        "ruleset_version": POC_RULESET_VERSION,
        "policy": "provisional_fallback",
        "official": False,
        "timestamp": device.get("timestamp"),
        "evidence": evidence,
        "source": {
            "inventory": device.get("inventory_source"),
            "telemetry": "datamgmt.CIN.con",
        },
        "disclaimer": POC_RULE_DISCLAIMER,
    }


def evaluate_status_rule(device, rule):
    status = str(device.get("status") or "").strip().lower()

    if status not in set(rule["threshold"]):
        return None

    return build_alert(
        device,
        rule,
        rule["severity"],
        {
            "field": "status",
            "value": status,
            "operator": rule["operator"],
            "threshold": rule["threshold"],
        },
    )


def evaluate_numeric_rule(device, rule):
    accepted_names = set(rule["metric_names"])
    matches = []

    for metric in device.get("metrics") or []:
        if metric_leaf_name(metric.get("name")) not in accepted_names:
            continue

        value = numeric_value(metric.get("value"))

        if value is None:
            continue

        matches.append((metric, value))

    if not matches:
        return None

    if rule["operator"] == ">=":
        metric, value = max(matches, key=lambda item: item[1])

        if value >= rule["critical_threshold"]:
            severity = "critical"
            threshold = rule["critical_threshold"]
        elif value >= rule["warning_threshold"]:
            severity = "warning"
            threshold = rule["warning_threshold"]
        else:
            return None
    else:
        metric, value = min(matches, key=lambda item: item[1])

        if value <= rule["critical_threshold"]:
            severity = "critical"
            threshold = rule["critical_threshold"]
        elif value <= rule["warning_threshold"]:
            severity = "warning"
            threshold = rule["warning_threshold"]
        else:
            return None

    return build_alert(
        device,
        rule,
        severity,
        {
            "field": metric.get("name"),
            "value": value,
            "unit": metric.get("unit") or "",
            "operator": rule["operator"],
            "threshold": threshold,
        },
    )


def evaluate_company_poc_rules(devices):
    alerts = []

    for device in devices:
        for rule in POC_RULES:
            if rule["signal"] == "status":
                alert = evaluate_status_rule(device, rule)
            else:
                alert = evaluate_numeric_rule(device, rule)

            if alert:
                alerts.append(alert)

    severity_order = {"critical": 0, "warning": 1}
    alerts.sort(key=lambda alert: (
        severity_order.get(alert["severity"], 9),
        str(alert.get("device_name") or alert.get("device_id") or ""),
    ))
    critical_count = len([
        alert for alert in alerts
        if alert["severity"] == "critical"
    ])
    warning_count = len([
        alert for alert in alerts
        if alert["severity"] == "warning"
    ])
    devices_with_telemetry = len([
        device for device in devices
        if device.get("telemetry_record_count")
    ])
    inventory_only_devices = len(devices) - devices_with_telemetry

    return {
        "critical_count": critical_count,
        "warning_count": warning_count,
        "total_count": len(alerts),
        "rules_status": "provisional_poc",
        "policy": "provisional_fallback",
        "official": False,
        "ruleset_version": POC_RULESET_VERSION,
        "rule_count": len(POC_RULES),
        "active_alerts": alerts,
        "operational_findings": {
            "devices_with_telemetry": devices_with_telemetry,
            "inventory_only_devices": inventory_only_devices,
        },
        "message": POC_RULE_DISCLAIMER,
    }


def get_company_poc_rule_catalog():
    return {
        "ruleset_version": POC_RULESET_VERSION,
        "policy": "provisional_fallback",
        "official": False,
        "rules": POC_RULES,
        "disclaimer": POC_RULE_DISCLAIMER,
    }
