create table if not exists public.telegram_identities (
  id integer primary key generated by default as identity,
  telegram_user_id text not null unique,
  user_id integer not null references public.users(id) on delete cascade,
  telegram_username text,
  role text not null default 'viewer',
  allowed_data_sources text not null default 'simulator',
  is_active boolean not null default true,
  created_at text not null,
  updated_at text not null
);

create index if not exists telegram_identities_user_id_idx
  on public.telegram_identities (user_id);

alter table public.telegram_identities enable row level security;

revoke all privileges on table public.telegram_identities from anon, authenticated;
revoke all privileges on sequence public.telegram_identities_id_seq from anon, authenticated;
