create table if not exists public.users (
  id integer primary key generated by default as identity,
  username text not null unique,
  password_hash text not null,
  created_at text not null
);

create table if not exists public.chats (
  id integer primary key generated by default as identity,
  user_id integer references public.users(id) on delete cascade,
  title text not null,
  created_at text not null,
  is_pinned boolean not null default false
);

create index if not exists chats_user_pinned_id_idx
  on public.chats (user_id, is_pinned desc, id desc);

create table if not exists public.messages (
  id integer primary key generated by default as identity,
  chat_id integer not null references public.chats(id) on delete cascade,
  role text not null,
  content text not null,
  reasoning_steps text,
  token_usage text,
  created_at text not null
);

alter table public.messages
  add column if not exists token_usage text;

create index if not exists messages_chat_id_idx
  on public.messages (chat_id, id asc);

create table if not exists public.prompts (
  id integer primary key generated by default as identity,
  user_id integer not null references public.users(id) on delete cascade,
  title text not null,
  command text not null,
  category text not null,
  is_default boolean not null default false,
  created_at text not null default to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS')
);

create index if not exists prompts_user_default_id_idx
  on public.prompts (user_id, is_default desc, id desc);

create table if not exists public.telegram_identities (
  id integer primary key generated by default as identity,
  telegram_user_id text not null unique,
  user_id integer not null references public.users(id) on delete cascade,
  telegram_username text,
  role text not null default 'viewer',
  allowed_data_sources text not null default 'simulator',
  is_active boolean not null default true,
  created_at text not null,
  updated_at text not null
);

create index if not exists telegram_identities_user_id_idx
  on public.telegram_identities (user_id);
