create table if not exists public.telegram_link_codes (
  id integer primary key generated by default as identity,
  code_hash text not null unique,
  user_id integer not null references public.users(id) on delete cascade,
  expires_at text not null,
  used_at text,
  created_at text not null
);

create index if not exists telegram_link_codes_user_id_idx
  on public.telegram_link_codes (user_id);

alter table public.telegram_link_codes enable row level security;

revoke all privileges on table public.telegram_link_codes from anon, authenticated;
revoke all privileges on sequence public.telegram_link_codes_id_seq from anon, authenticated;
